In [19]:
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

In [2]:
dataset =  pd.read_csv("datasets/weight-height.csv")

In [3]:
dataset.columns

Index(['Gender', 'Height', 'Weight'], dtype='object')

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Gender  10000 non-null  object 
 1   Height  10000 non-null  float64
 2   Weight  10000 non-null  float64
dtypes: float64(2), object(1)
memory usage: 234.5+ KB


In [5]:
dataset.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [6]:
X = dataset["Height"]

In [7]:
y = dataset["Weight"]

In [9]:
model = Sequential()

In [10]:
model.summary()

ValueError: This model has not yet been built. Build the model first by calling `build()` or calling `fit()` with some data, or specify an `input_shape` argument in the first layer(s) for automatic build.

In [12]:
# One dense function will create one hidden layer.
Dense( units=1,  activation='linear', input_shape=(1,) )

In [16]:
model.add(Dense( units=1,  activation='linear', input_shape=(1,),
                 bias_initializer="zeros",
                 kernel_initializer="zeros" 
               ))

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 1)                 2         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 2         
Total params: 4
Trainable params: 4
Non-trainable params: 0
_________________________________________________________________


In [18]:
model.get_config()

{'name': 'sequential',
 'layers': [{'class_name': 'InputLayer',
   'config': {'batch_input_shape': (None, 1),
    'dtype': 'float32',
    'sparse': False,
    'ragged': False,
    'name': 'dense_1_input'}},
  {'class_name': 'Dense',
   'config': {'name': 'dense_1',
    'trainable': True,
    'batch_input_shape': (None, 1),
    'dtype': 'float32',
    'units': 1,
    'activation': 'linear',
    'use_bias': True,
    'kernel_initializer': {'class_name': 'GlorotUniform',
     'config': {'seed': None}},
    'bias_initializer': {'class_name': 'Zeros', 'config': {}},
    'kernel_regularizer': None,
    'bias_regularizer': None,
    'activity_regularizer': None,
    'kernel_constraint': None,
    'bias_constraint': None}},
  {'class_name': 'Dense',
   'config': {'name': 'dense_2',
    'trainable': True,
    'batch_input_shape': (None, 1),
    'dtype': 'float32',
    'units': 1,
    'activation': 'linear',
    'use_bias': True,
    'kernel_initializer': {'class_name': 'Zeros', 'config': {}},
 

In [15]:
model.fit(X,y)

RuntimeError: You must compile your model before training/testing. Use `model.compile(optimizer, loss)`.

In [20]:
model.compile(optimizer=Adam(), loss="mean_squared_error")

In [21]:
model.fit(X,y)

313/313 [==============================] - 0s 456us/step - loss: 21762.9688


In [22]:
model.get_weights()

[array([[-1.8577888]], dtype=float32),
 array([-0.46124983], dtype=float32),
 array([[-0.31353137]], dtype=float32),
 array([0.29399866], dtype=float32)]

In [26]:
model.predict([100])

array([[58.68612]], dtype=float32)

In [27]:
model.save("myheight_weight.h5")

In [35]:
model.get_layer("dense_1").output

<tf.Tensor 'dense_1/BiasAdd:0' shape=(None, 1) dtype=float32>