In [28]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import joblib

In [7]:
dataset = pd.read_csv("datasets/marks.csv")

In [9]:
dataset

name  hours  marks
0  rahul      8     80
1   eric      9     90
2    tom      6     60
3    raj      5     50
4  sayan      7     70

In [14]:
X = dataset["hours"]

In [15]:
y = dataset["marks"]

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [17]:
X_train

2    6
0    8
3    5
Name: hours, dtype: int64

In [18]:
model = LinearRegression()

In [19]:
model.fit(X_train, y_train )

ValueError: Expected 2D array, got 1D array instead:
array=[6 8 5].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [20]:
type(X_train)

pandas.core.series.Series

In [21]:
X_train.values

array([6, 8, 5], dtype=int64)

In [24]:
X_train = X_train.values.reshape(-1,1)

In [25]:
model.fit(X_train, y_train )

LinearRegression()

In [26]:
model.predict([[10]])

array([100.])

In [27]:
model.coef_

array([10.])

In [29]:
#Saving the model

joblib.dump(model, "marks.pk1")

['marks.pk1']